services:
  Home\CompleteeBundle\Controller\CompleteeController:
    class: Home\CompleteeBundle\Controller\CompleteeController
    tags: ['controller.service_arguments']
    calls:
      - ['setContainer', ['@service_container']]
